### ISSUE TITLE
Feature.id

### ISSUE THREAD

**Issue by pmpowers-usgs** [bclayton-usgs/nshmp-site-ws#16]
Have `Feature` carry an `Optional<?> id;` field, consistent with the geojson spec. Although the value will often be numeric, it could also be a String. Maybe `Feature` provides `getId()` and `getNumericId()`, which return String and int, respectively. I think that how this is a function of how Features are deserialized.

**Comment by bclayton-usgs** [comment]
Resolved by usgs/nshmp-haz#320
