### ISSUE TITLE
Add tests for basin service

### ISSUE THREAD

**Issue by pmpowers-usgs** [bclayton-usgs/nshmp-site-ws#28]
We want to check about 2 sites per basin and 2 sites outside any basin to check that results coming back from the service match expectations. @pmpowers-usgs needs to provide values to check against.

**Comment by bclayton-usgs** [comment]
From #31 

Add tests for the following sites (from NshmpSite.java):

```
    List<NshmpSite> locations = ImmutableList.of(
        
        // LA Basin
        LOS_ANGELES_CA,
        NORTHRIDGE_CA,
        
        // Bay Area
        SAN_FRANCISCO_CA,
        SAN_JOSE_CA,
        OAKLAND_CA,
        
        // Wasatch Front
        SALT_LAKE_CITY_UT,
        PROVO_UT,
        
        // Puget Lowland
        SEATTLE_WA,
        TACOMA_WA,
        
        // Outside basin (null expected)
        ELKO_NV);
```

Run the service against the sites to get the current values and then hard code into the test case.
